version: '3.8'

services:
  geoapi:
    image: ${DOCKER_REGISTRY-}geoapi
    container_name: geoAPI
    build:
      context: .
      dockerfile: geoAPI/Dockerfile
    depends_on:
      - geoAPI.db

  geoAPI.db:
    image: postgis/postgis
    container_name: geoAPI.db
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: notapassword
      POSTGRES_USER: test_api
      POSTGRES_DB: test_db
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: